"""
Table lists for all rhizome databases.

This module defines all tables tracked across different databases
and environments in rhizome.
"""

from __future__ import annotations

from enum import StrEnum, auto


class BillingTable(StrEnum):
    """Table identifiers for billing database."""

    stage_charge = auto()
    app_suppression = auto()
    auto_debit_no_auth_config = auto()
    bank_routing = auto()
    banner_curb = auto()
    banner_data = auto()
    banner_details = auto()
    bi_context = auto()
    biie_config = auto()
    biie_file_def = auto()
    biie_file_instance = auto()
    biie_file_instance_request = auto()
    biie_file_staging_data = auto()
    billing_business_initiative = auto()
    billing_request = auto()
    billing_request_state = auto()
    charge_capture_error = auto()
    charge_invoice_number = auto()
    charge_metrics = auto()
    charge_post_date = auto()
    charge_state_attempt = auto()
    combined_charge = auto()
    combined_charge_tree = auto()
    combined_disbursement = auto()
    combined_disbursement_tree = auto()
    corollary_data = auto()
    country_suppression = auto()
    device_order_tracking = auto()
    disbursement_invoice_number = auto()
    email_audit = auto()
    email_developer_charge = auto()
    explanation = auto()
    explanation_data = auto()
    export_tracker = auto()
    fee = auto()
    fee_exception = auto()
    flight_check = auto()
    flight_check_archive = auto()
    flight_check_execution = auto()
    heartbeat = auto()
    invoice_charge = auto()
    job_lock = auto()
    merchant_device_info = auto()
    merchant_odessa_mapping = auto()
    merchant_queue_sensitive = auto()
    merchant_subscription_action = auto()
    merchant_suppression = auto()
    merchant_suppression_by_app = auto()
    merchant_terms_acceptance = auto()
    merchant_terms_acceptance_events = auto()
    merchant_terms_acceptance_failed_event_log = auto()
    merchant_terms_missing_acceptance = auto()
    offboarding = auto()
    plan_authorization_settings = auto()
    plan_meta = auto()
    plan_meta_history = auto()
    producer_failure = auto()
    promo = auto()
    promo_control = auto()
    remit_merchant_details = auto()
    reseller_app_rev_share = auto()
    reseller_invoice_alliance = auto()
    reseller_plan_fee = auto()
    reseller_plan_rev_share = auto()
    reseller_suppression = auto()
    reseller_usage_job_config = auto()
    rev_share = auto()
    seasonal_merchant_trans_audit = auto()
    seasonal_reseller_info = auto()
    server_config = auto()
    stage_app_metered_event = auto()
    stage_charge_capture_error = auto()
    stage_charge_history = auto()
    stage_charge_state_attempt = auto()
    stage_charge_update = auto()
    stage_email = auto()
    stage_email_merchant_charge = auto()
    stage_infolease_charge_attempt = auto()
    stage_infolease_disbursement_attempt = auto()
    stage_merchant_app_charge = auto()
    stage_merchant_plan_charge = auto()
    stage_vendor_disbursement_error = auto()
    stage_vendor_disbursement_state_attempt = auto()
    stop_ach_history = auto()
    suppression_metrics = auto()
    vat_vendor_disbursement = auto()
    vendor_disbursement_error = auto()
    vendor_disbursement_state_attempt = auto()


class BillingBookkeeperTable(StrEnum):
    """Table identifiers for billing_bookkeeper database."""

    billing_entity = auto()
    fee_rate = auto()
    fee_summary = auto()
    invoice_info = auto()
    settlement = auto()


class BillingEventTable(StrEnum):
    """Table identifiers for billing_event database."""

    app_metered_event = auto()
    app_subscription_current = auto()
    app_subscription_daily = auto()
    app_subscription_event = auto()
    as_of_merchant = auto()
    as_of_merchant_device = auto()
    as_of_merchant_plan = auto()
    backfill_acceptance = auto()
    billing_event_history = auto()
    cellular_arrears_acceptances = auto()
    cellular_billing_arrears_info = auto()
    consumer_failure = auto()
    consumer_failure_history = auto()
    deserializable_failure = auto()
    event_filter = auto()
    event_ignored = auto()
    iccid_carrier = auto()
    job_assassination_contract = auto()
    jobrunr_backgroundjobservers = auto()
    jobrunr_jobs = auto()
    jobrunr_metadata = auto()
    jobrunr_migrations = auto()
    jobrunr_recurring_jobs = auto()
    look = auto()
    look_data = auto()
    managed_item = auto()
    merchant_acceptance = auto()
    merchant_evolution = auto()
    merchant_offboarding = auto()
    merchant_payment = auto()
    merchant_payment_history = auto()
    migrated_merchant = auto()
    mlc_captured_event = auto()
    pending_event = auto()
    plan_billing_latest = auto()
    plan_meta = auto()
    plan_trial = auto()
    producer_failure = auto()
    producer_failure_history = auto()
    server_config = auto()
    test_merchant_criteria = auto()
    uninstalled_app = auto()


class MetaTable(StrEnum):
    """Table identifiers for the meta database."""

    account = auto()
    country = auto()
    device_type = auto()
    server_feature = auto()
    merchant = auto()
    terminal_config_merchant_props = auto()
    reseller = auto()
    merchant_address = auto()
    merchant_gateway = auto()
    payment_processor = auto()
    processor_key = auto()
    merchant_plan = auto()
    app_bundle = auto()
    app_app_bundle = auto()
    merchant_plan_merchant_plan_group = auto()
    merchant_plan_group = auto()
    merchant_role = auto()
    locale = auto()
    timezones = auto()
    merchant_boarding = auto()
    merchant_creation_details = auto()
    device_provision = auto()
    device_events = auto()
    merchant_merchant_plan_history = auto()
    reseller_plan_trial = auto()
    merchant_app_subscription_history = auto()
    merchant_app = auto()
    developer_app = auto()
    app_permission = auto()
    developer = auto()
    app_subscription = auto()
    app_subscription_country = auto()
    app_metered_event = auto()
    app_metered = auto()
    app_metered_country = auto()
