"""
Proxied wrapper functions for billing-bookkeeper dev - cellular_action_fee_rate.

Auto-generated by stolon sync spec.
These wrappers route requests through the stolon server for automatic
token management, logging, and retry logic.
"""

import contextlib
import json
from http import HTTPStatus

from stolon.client import StolonClient
from stolon.generated.billing_bookkeeper_dev.open_api_definition_client.api.cellular_action_fee_rate import (
    get_fee_descriptions_for_merchant_cellular_plan,
)
from stolon.generated.billing_bookkeeper_dev.open_api_definition_client.models.api_cellular_action_fee_code_detail import (
    ApiCellularActionFeeCodeDetail,
)
from stolon.generated.billing_bookkeeper_dev.open_api_definition_client.types import Response


def get_fee_descriptions_for_merchant_cellular_plan_sync_detailed(
    *, client: StolonClient, uuid: str
) -> Response[ApiCellularActionFeeCodeDetail]:
    """Get fee descriptions for the provided merchants cellular plan

    Args:
        uuid (str):
        plan_uuid (Union[Unset, str]):
        carrier (Union[Unset, str]):
        effective_date (Union[Unset, datetime.date]):
        currency (Union[Unset, str]):
        accept_language (Union[Unset, str]):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[ApiCellularActionFeeCodeDetail]

    This function wraps the generated OpenAPI client to proxy requests through
    the stolon server, enabling automatic token management and logging.

    Args:
        client: StolonClient instance for proxying requests
                uuid: str

    Returns:
        Response[ApiCellularActionFeeCodeDetail]
    """
    # Extract request parameters from generated function
    kwargs = get_fee_descriptions_for_merchant_cellular_plan._get_kwargs(uuid=uuid)

    # Proxy request through stolon server
    proxy_response = client.proxy_request(
        domain="dev1.dev.clover.com",
        method=kwargs["method"],
        path=kwargs["url"],
        environment_name="dev",
        json_body=kwargs.get("json"),
        params=kwargs.get("params"),
        timeout=30.0,
    )

    # Parse response into Response object (detailed variant)
    from stolon.generated.billing_bookkeeper_dev.open_api_definition_client.types import Response

    # Parse body if JSON
    body_json = None
    if proxy_response.body:
        with contextlib.suppress(json.JSONDecodeError):
            body_json = json.loads(proxy_response.body)

    # Parse response using generated function's parser
    if body_json and proxy_response.status_code == 200 and ApiCellularActionFeeCodeDetail:
        parsed = ApiCellularActionFeeCodeDetail.from_dict(body_json)
    else:
        parsed = None

    return Response(
        status_code=HTTPStatus(proxy_response.status_code),
        content=proxy_response.body.encode("utf-8") if proxy_response.body else b"",
        headers=proxy_response.headers,
        parsed=parsed,
    )


def get_fee_descriptions_for_merchant_cellular_plan_sync(
    *, client: StolonClient, uuid: str
) -> ApiCellularActionFeeCodeDetail | None:
    """Get fee descriptions for the provided merchants cellular plan

    Args:
        uuid (str):
        plan_uuid (Union[Unset, str]):
        carrier (Union[Unset, str]):
        effective_date (Union[Unset, datetime.date]):
        currency (Union[Unset, str]):
        accept_language (Union[Unset, str]):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        ApiCellularActionFeeCodeDetail

    This function wraps the generated OpenAPI client to proxy requests through
    the stolon server, enabling automatic token management and logging.

    Args:
        client: StolonClient instance for proxying requests
                uuid: str

    Returns:
        ApiCellularActionFeeCodeDetail | None
    """
    # Extract request parameters from generated function
    kwargs = get_fee_descriptions_for_merchant_cellular_plan._get_kwargs(uuid=uuid)

    # Proxy request through stolon server
    proxy_response = client.proxy_request(
        domain="dev1.dev.clover.com",
        method=kwargs["method"],
        path=kwargs["url"],
        environment_name="dev",
        json_body=kwargs.get("json"),
        params=kwargs.get("params"),
        timeout=30.0,
    )

    # Parse response body

    if proxy_response.body and proxy_response.status_code == 200:
        try:
            body_json = json.loads(proxy_response.body)
            return ApiCellularActionFeeCodeDetail.from_dict(body_json)
        except (json.JSONDecodeError, KeyError, TypeError):
            pass
    return None


def get_fee_descriptions_for_merchant_cellular_plan_asyncio_detailed(
    *, client: StolonClient, uuid: str
) -> Response[ApiCellularActionFeeCodeDetail]:
    """Get fee descriptions for the provided merchants cellular plan

    Args:
        uuid (str):
        plan_uuid (Union[Unset, str]):
        carrier (Union[Unset, str]):
        effective_date (Union[Unset, datetime.date]):
        currency (Union[Unset, str]):
        accept_language (Union[Unset, str]):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[ApiCellularActionFeeCodeDetail]

    This function wraps the generated OpenAPI client to proxy requests through
    the stolon server, enabling automatic token management and logging.

    Args:
        client: StolonClient instance for proxying requests
                uuid: str

    Returns:
        Response[ApiCellularActionFeeCodeDetail]
    """
    # Extract request parameters from generated function
    kwargs = get_fee_descriptions_for_merchant_cellular_plan._get_kwargs(uuid=uuid)

    # Proxy request through stolon server
    proxy_response = client.proxy_request(
        domain="dev1.dev.clover.com",
        method=kwargs["method"],
        path=kwargs["url"],
        environment_name="dev",
        json_body=kwargs.get("json"),
        params=kwargs.get("params"),
        timeout=30.0,
    )

    # Parse response into Response object (detailed variant)
    from stolon.generated.billing_bookkeeper_dev.open_api_definition_client.types import Response

    # Parse body if JSON
    body_json = None
    if proxy_response.body:
        with contextlib.suppress(json.JSONDecodeError):
            body_json = json.loads(proxy_response.body)

    # Parse response using generated function's parser
    if body_json and proxy_response.status_code == 200 and ApiCellularActionFeeCodeDetail:
        parsed = ApiCellularActionFeeCodeDetail.from_dict(body_json)
    else:
        parsed = None

    return Response(
        status_code=HTTPStatus(proxy_response.status_code),
        content=proxy_response.body.encode("utf-8") if proxy_response.body else b"",
        headers=proxy_response.headers,
        parsed=parsed,
    )


def get_fee_descriptions_for_merchant_cellular_plan_asyncio(
    *, client: StolonClient, uuid: str
) -> ApiCellularActionFeeCodeDetail | None:
    """Get fee descriptions for the provided merchants cellular plan

    Args:
        uuid (str):
        plan_uuid (Union[Unset, str]):
        carrier (Union[Unset, str]):
        effective_date (Union[Unset, datetime.date]):
        currency (Union[Unset, str]):
        accept_language (Union[Unset, str]):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        ApiCellularActionFeeCodeDetail

    This function wraps the generated OpenAPI client to proxy requests through
    the stolon server, enabling automatic token management and logging.

    Args:
        client: StolonClient instance for proxying requests
                uuid: str

    Returns:
        ApiCellularActionFeeCodeDetail | None
    """
    # Extract request parameters from generated function
    kwargs = get_fee_descriptions_for_merchant_cellular_plan._get_kwargs(uuid=uuid)

    # Proxy request through stolon server
    proxy_response = client.proxy_request(
        domain="dev1.dev.clover.com",
        method=kwargs["method"],
        path=kwargs["url"],
        environment_name="dev",
        json_body=kwargs.get("json"),
        params=kwargs.get("params"),
        timeout=30.0,
    )

    # Parse response body

    if proxy_response.body and proxy_response.status_code == 200:
        try:
            body_json = json.loads(proxy_response.body)
            return ApiCellularActionFeeCodeDetail.from_dict(body_json)
        except (json.JSONDecodeError, KeyError, TypeError):
            pass
    return None
