CREATE TABLE `cellular_action` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `uuid` char(26) NOT NULL,
  `billing_entity_uuid` char(26) NOT NULL,
  `merchant_plan_uuid` varchar(13) DEFAULT NULL,
  `iccid` varchar(24) NOT NULL,
  `carrier` varchar(25) NOT NULL,
  `cellular_action_type` varchar(25) NOT NULL,
  `fee_category` varchar(25) NOT NULL,
  `fee_code` varchar(25) NOT NULL,
  `action_datetime` datetime(6) NOT NULL,
  `num_units` smallint NOT NULL DEFAULT '0',
  `units_in_period` smallint unsigned NOT NULL,
  `basis_amount` decimal(12,3) DEFAULT '0.000',
  `basis_currency` char(3) DEFAULT NULL,
  `reference` varchar(50) DEFAULT NULL,
  `cellular_action_fee_code_uuid` char(26) DEFAULT NULL,
  `fee_uuid` char(26) DEFAULT NULL,
  `event_uuid` char(26) DEFAULT NULL,
  `request_uuid` char(26) DEFAULT NULL,
  `date_to_post` date DEFAULT NULL,
  `posting_date` date DEFAULT NULL,
  `created_timestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `modified_timestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `cellular_action_key1` (`uuid`),
  UNIQUE KEY `cellular_action_key2` (`billing_entity_uuid`,`date_to_post`,`fee_uuid`,`fee_category`,`fee_code`,`uuid`),
  UNIQUE KEY `cellular_action_key3` (`request_uuid`,`billing_entity_uuid`,`uuid`),
  KEY `cellular_action_key4` (`fee_uuid`,`action_datetime`)
) ENGINE=InnoDB AUTO_INCREMENT=227 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci