CREATE TABLE `merchant_acceptance` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `uuid` char(26) NOT NULL,
  `merchant_uuid` char(13) NOT NULL,
  `account_id` char(13) NOT NULL,
  `acceptance_id` char(36) NOT NULL,
  `agreement_id` char(36) NOT NULL,
  `agreement_type` varchar(25) NOT NULL,
  `agreement_event_type` enum('CREATED','INVALIDATED') NOT NULL,
  `action` enum('ACCEPTED','STALE','REVOKED','DECLINED','REREQUESTED','OFFBOARDED','UNKNOWN') NOT NULL,
  `acceptance_created_datetime` datetime DEFAULT NULL,
  `acceptance_modified_datetime` datetime DEFAULT NULL,
  `acceptance_deleted_datetime` datetime DEFAULT NULL,
  `acceptance_expiration_datetime` datetime DEFAULT NULL,
  `serial_number` varchar(32) DEFAULT NULL,
  `iccid` varchar(22) DEFAULT NULL,
  `is_oobe` tinyint(1) DEFAULT NULL,
  `created_timestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `modified_timestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `merchant_acceptance_key1` (`uuid`),
  UNIQUE KEY `merchant_acceptance_key3` (`acceptance_id`),
  UNIQUE KEY `merchant_acceptance_key2` (`merchant_uuid`,`agreement_type`,`serial_number`,`id` DESC)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci