CREATE TABLE `billing_hierarchy_cycle` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `uuid` char(26) NOT NULL,
  `processing_group_uuid` char(26) NOT NULL,
  `billing_hierarchy_uuid` char(26) NOT NULL,
  `cycle_date` date NOT NULL,
  `close_date` date DEFAULT NULL,
  `effective_close_date` date DEFAULT NULL,
  `billing_entity_uuid` char(26) NOT NULL,
  `entity_uuid` varchar(13) NOT NULL,
  `schedule_parent_be_uuid` char(26) NOT NULL,
  `fee_rate_parent_be_uuid` char(26) NOT NULL,
  `frequency` enum('NO_BILL','MONTHLY') NOT NULL,
  `billing_day` smallint NOT NULL,
  `next_billing_date` date NOT NULL,
  `last_billing_date` date DEFAULT NULL,
  `arrears_billing_date` date DEFAULT NULL,
  `units_in_next_period` smallint NOT NULL,
  `units_in_last_period` smallint DEFAULT NULL,
  `units_in_arrears_period` smallint DEFAULT NULL,
  `default_currency` char(3) NOT NULL,
  `post_method` varchar(20) NOT NULL,
  `plan_billing_method` varchar(20) NOT NULL,
  `invoice_method` varchar(20) NOT NULL,
  `invoice_number_format` varchar(20) NOT NULL,
  `settlement_method` varchar(20) NOT NULL,
  `created_timestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `modified_timestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `billing_hierarchy_cycle_key1` (`uuid`),
  UNIQUE KEY `billing_hierarchy_cycle_key3` (`billing_entity_uuid`,`cycle_date` DESC),
  UNIQUE KEY `billing_hierarchy_cycle_key2` (`processing_group_uuid`,`billing_hierarchy_uuid`,`cycle_date` DESC,`schedule_parent_be_uuid`,`billing_entity_uuid`)
) ENGINE=InnoDB AUTO_INCREMENT=319903 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci