CREATE TABLE `auto_adjust_advice` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `uuid` char(26) NOT NULL,
  `billing_entity_uuid` char(26) NOT NULL,
  `auto_adjust_rule_uuid` char(26) NOT NULL,
  `start_date` date NOT NULL,
  `deleted_date` date DEFAULT NULL,
  `total_periods` smallint NOT NULL,
  `evaluated_periods` smallint NOT NULL DEFAULT '0',
  `applied_periods` smallint NOT NULL DEFAULT '0',
  `max_units` decimal(12,4) DEFAULT NULL,
  `max_amount` decimal(12,3) DEFAULT NULL,
  `currency` varchar(3) DEFAULT NULL,
  `reference` varchar(50) DEFAULT NULL,
  `request_uuid` varchar(26) DEFAULT NULL,
  `created_timestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `modified_timestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `audit_id` varchar(26) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `auto_adjust_advice_key1` (`uuid`),
  UNIQUE KEY `auto_adjust_advice_key2` (`billing_entity_uuid`,`start_date`,`deleted_date`,`auto_adjust_rule_uuid`,`id`),
  UNIQUE KEY `auto_adjust_advice_key3` (`auto_adjust_rule_uuid`,`billing_entity_uuid`,`start_date`,`deleted_date`,`id`),
  UNIQUE KEY `auto_adjust_advice_key4` (`request_uuid`,`billing_entity_uuid`,`auto_adjust_rule_uuid`,`id`)
) ENGINE=InnoDB AUTO_INCREMENT=111 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci