CREATE TABLE `stage_charge_update` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `charge_id` bigint unsigned NOT NULL,
  `merchant_id` bigint unsigned DEFAULT NULL,
  `status` enum('PENDING','IN_PROGRESS','BILLED','CANCELED','REFUND_PENDING','REFUND_PENDING_IF_BILLED','REFUND_IN_PROGRESS','REFUNDED','REFUND_DOWNGRADE_PENDING','REFUND_DOWNGRADE_IN_PROGRESS','REFUND_DOWNGRADE_CANCELED','REFUNDED_DOWNGRADE','DISBURSED','ACH_REJECT','RESUBMITTED','INCURRED','REFUND_INCURRED','REFUND_INCURRED_IF_BILLED','REFUND_DOWNGRADE_INCURRED','REFUND_ACH_REJECT','REFUND_DOWNGRADE_ACH_REJECT','REFUND_CANCELED','WAIVED','REFUND_WAIVED','REFUND_DOWNGRADE_WAIVED','WRITTEN_OFF','REFUND_WRITTEN_OFF','REFUND_DOWNGRADE_WRITTEN_OFF','REVERSED','REFUND_REVERSED','REFUND_DOWNGRADE_REVERSED') NOT NULL,
  `developer_status` enum('DISBURSED','DISBURSE_FAILED','DISBURSE_PENDING','RECLAIMED','RECLAIM_FAILED','RECLAIM_PENDING') DEFAULT NULL,
  `tax` bigint DEFAULT NULL,
  `developer_portion` bigint DEFAULT NULL,
  `status_owner` varchar(30) NOT NULL,
  `request_uuid` char(13) NOT NULL,
  `promoted_time` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `scu_idx1` (`charge_id`,`promoted_time`,`id`),
  KEY `request_uuid` (`request_uuid`)
) ENGINE=InnoDB AUTO_INCREMENT=879 DEFAULT CHARSET=utf8mb3