CREATE TABLE `partner_config` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `uuid` char(26) NOT NULL,
  `billing_entity_uuid` char(26) NOT NULL,
  `hierarchy_type` varchar(20) NOT NULL,
  `effective_date` date NOT NULL,
  `revenue_share_group` varchar(20) DEFAULT NULL,
  `post_method` varchar(20) DEFAULT NULL,
  `plan_billing_method` varchar(20) DEFAULT NULL,
  `invoice_method` varchar(20) DEFAULT NULL,
  `invoice_number_format` varchar(20) DEFAULT NULL,
  `settlement_method` varchar(20) DEFAULT NULL,
  `seasonal_rule_set_uuid` varchar(26) DEFAULT NULL,
  `created_timestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `modified_timestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `audit_id` varchar(26) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `partner_config_key1` (`uuid`),
  UNIQUE KEY `partner_config_key2` (`billing_entity_uuid`,`hierarchy_type`,`effective_date`),
  UNIQUE KEY `partner_config_key3` (`seasonal_rule_set_uuid`,`billing_entity_uuid`,`hierarchy_type`,`effective_date`,`id`)
) ENGINE=InnoDB AUTO_INCREMENT=71 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci