CREATE TABLE `settlement_mutation` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `mutation_action` enum('UPDATE','DELETE') NOT NULL,
  `mutation_timestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `settlement_id` bigint unsigned NOT NULL,
  `uuid` char(26) NOT NULL,
  `settlement_date` date DEFAULT NULL,
  `billing_entity_uuid` char(26) DEFAULT NULL,
  `entity_uuid` char(13) DEFAULT NULL,
  `alternate_id` varchar(30) DEFAULT NULL,
  `payable_receivable` enum('PAYABLE','RECEIVABLE') DEFAULT NULL,
  `currency` char(3) DEFAULT NULL,
  `total_amount` decimal(12,3) DEFAULT NULL,
  `fee_amount` decimal(12,3) DEFAULT NULL,
  `tax1_amount` decimal(12,3) DEFAULT NULL,
  `tax2_amount` decimal(12,3) DEFAULT NULL,
  `tax3_amount` decimal(12,3) DEFAULT NULL,
  `tax4_amount` decimal(12,3) DEFAULT NULL,
  `lookup_ledger_account_key` varchar(32) DEFAULT NULL,
  `gl_code` varchar(40) DEFAULT NULL,
  `item_code` varchar(30) DEFAULT NULL,
  `last_invoice_num` varchar(30) DEFAULT NULL,
  `request_uuid` char(26) DEFAULT NULL,
  `created_timestamp` datetime(6) DEFAULT NULL,
  `modified_timestamp` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `settlement_mutation_key1` (`uuid`,`id`)
) ENGINE=InnoDB AUTO_INCREMENT=694 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci