CREATE TABLE `settlement` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `uuid` char(26) NOT NULL,
  `settlement_date` date NOT NULL,
  `billing_entity_uuid` char(26) NOT NULL,
  `entity_uuid` char(13) NOT NULL,
  `alternate_id` varchar(30) DEFAULT NULL,
  `payable_receivable` enum('PAYABLE','RECEIVABLE') NOT NULL,
  `currency` char(3) NOT NULL,
  `total_amount` decimal(12,3) NOT NULL,
  `fee_amount` decimal(12,3) NOT NULL,
  `tax1_amount` decimal(12,3) NOT NULL DEFAULT '0.000',
  `tax2_amount` decimal(12,3) NOT NULL DEFAULT '0.000',
  `tax3_amount` decimal(12,3) NOT NULL DEFAULT '0.000',
  `tax4_amount` decimal(12,3) NOT NULL DEFAULT '0.000',
  `lookup_ledger_account_key` varchar(32) NOT NULL,
  `gl_code` varchar(40) DEFAULT NULL,
  `item_code` varchar(30) DEFAULT NULL,
  `last_invoice_num` varchar(30) DEFAULT NULL,
  `request_uuid` char(26) DEFAULT NULL,
  `created_timestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `modified_timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `settlement_key1` (`uuid`),
  UNIQUE KEY `settlement_key2` (`billing_entity_uuid`,`settlement_date` DESC,`id`),
  UNIQUE KEY `settlement_key3` (`entity_uuid`,`settlement_date` DESC,`id`),
  UNIQUE KEY `settlement_key4` (`request_uuid`,`billing_entity_uuid`,`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4729 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci