CREATE TABLE `reseller` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `parent_id` bigint unsigned DEFAULT NULL,
  `uuid` char(13) CHARACTER SET latin1 NOT NULL,
  `fd_client_id` varchar(10) DEFAULT NULL,
  `name` varchar(127) NOT NULL,
  `alternate_name` varchar(127) DEFAULT NULL,
  `code` varchar(20) DEFAULT NULL,
  `owner_account_id` int unsigned NOT NULL,
  `default_payment_processor_id` bigint unsigned DEFAULT NULL,
  `default_processor_key_id` bigint unsigned DEFAULT NULL,
  `default_country_code` char(2) DEFAULT NULL,
  `supports_naked_credit` tinyint(1) DEFAULT '1',
  `created_time` timestamp NULL DEFAULT NULL,
  `modified_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `support_phone` varchar(25) DEFAULT '000-000-0000',
  `support_email` varchar(127) DEFAULT NULL,
  `filter_apps` tinyint(1) DEFAULT '0',
  `force_phone` tinyint(1) DEFAULT '0',
  `stations_on_classic` tinyint(1) NOT NULL DEFAULT '1',
  `allow_blackhole` tinyint(1) DEFAULT '0',
  `tasq_customer_number` char(7) DEFAULT NULL,
  `is_bulk_purchaser` tinyint(1) DEFAULT '0',
  `partner_support_email` varchar(127) DEFAULT NULL,
  `supports_outbound_boarding` tinyint(1) NOT NULL DEFAULT '0',
  `is_rki_identifier` tinyint(1) NOT NULL DEFAULT '0',
  `enforce_merchant_plan` tinyint(1) DEFAULT '0',
  `is_self_boarding` tinyint(1) DEFAULT '0',
  `is_intercom_enabled` tinyint(1) DEFAULT '1',
  `fdmp_configuration_id` int unsigned DEFAULT NULL,
  `locale_id` bigint unsigned DEFAULT NULL,
  `is_codeless_activation` tinyint(1) DEFAULT '0',
  `reseller_privacy_policy_url` varchar(2083) DEFAULT NULL,
  `feedback_disabled` tinyint(1) NOT NULL DEFAULT '0',
  `is_rapid_deposit_enabled` tinyint(1) NOT NULL DEFAULT '0',
  `rapid_deposit_service_entitlement_number` varchar(128) DEFAULT NULL,
  `prohibit_tokenization` tinyint(1) NOT NULL DEFAULT '0',
  `is_new_billing` tinyint unsigned NOT NULL DEFAULT '1',
  `plan_group_id` int unsigned DEFAULT NULL,
  `type` enum('AGENT','COMMUNITY_BANK','DEMO','DIRECT_SALES','FSP','JV','NON_FI','PFAC','REFERRAL_PARTNER','REGIONAL_FI','RETAIL_ISO','SMS','STRATEGIC_FI','UNKNOWN','WHOLESALE_ISO','COMBO','BOLT','GOOGLE','NON_PROCESSING') DEFAULT NULL,
  `source` enum('COPILOT','INTERNAL') NOT NULL DEFAULT 'INTERNAL',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uuid` (`uuid`),
  UNIQUE KEY `code` (`code`),
  KEY `plan_group_fk` (`plan_group_id`),
  KEY `reseller_ibfk_5` (`fdmp_configuration_id`),
  KEY `owner_account_id` (`owner_account_id`),
  KEY `default_payment_processor_id` (`default_payment_processor_id`),
  KEY `default_processor_key_id` (`default_processor_key_id`),
  KEY `name` (`name`),
  KEY `parent_id` (`parent_id`),
  KEY `alternate_name` (`alternate_name`),
  KEY `reseller_type` (`type`,`id`),
  CONSTRAINT `plan_group_fk` FOREIGN KEY (`plan_group_id`) REFERENCES `merchant_plan_group` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `reseller_ibfk_1` FOREIGN KEY (`owner_account_id`) REFERENCES `account` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `reseller_ibfk_2` FOREIGN KEY (`default_payment_processor_id`) REFERENCES `payment_processor` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `reseller_ibfk_3` FOREIGN KEY (`default_processor_key_id`) REFERENCES `processor_key` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `reseller_ibfk_4` FOREIGN KEY (`parent_id`) REFERENCES `reseller` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `reseller_ibfk_5` FOREIGN KEY (`fdmp_configuration_id`) REFERENCES `fdmp_configuration` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=21115 DEFAULT CHARSET=utf8mb3