CREATE TABLE `device_provision` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `serial_number` varchar(32) DEFAULT NULL,
  `chip_uid` varchar(32) CHARACTER SET latin1 DEFAULT NULL,
  `imei` varchar(15) CHARACTER SET latin1 DEFAULT NULL,
  `provision_info` text,
  `last_activation_code` char(8) CHARACTER SET latin1 DEFAULT NULL,
  `activation_code` char(8) CHARACTER SET latin1 DEFAULT NULL,
  `activation_code_created_time` timestamp NULL DEFAULT NULL,
  `deauthorization_code` char(8) CHARACTER SET latin1 DEFAULT NULL,
  `deauthorization_attempts` smallint DEFAULT '0',
  `merchant_id` int unsigned DEFAULT NULL,
  `reseller_id` bigint unsigned DEFAULT NULL,
  `email_sent` tinyint(1) DEFAULT '0',
  `sms_sent` tinyint(1) DEFAULT '0',
  `order_type` enum('NEW','SWAP') DEFAULT NULL,
  `provisioned_time` timestamp NULL DEFAULT NULL,
  `activated_time` timestamp NULL DEFAULT NULL,
  `terminal_id` varchar(8) DEFAULT NULL,
  `deleted_time` timestamp NULL DEFAULT NULL,
  `modified_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `shipping_status` enum('SHIPPED','DELIVERED','SHIPPING_ERROR','SHIPPING_CANCELLED','RETURN_TO_SENDER','READY_FOR_RETURN','RETURNED','WRITE_OFF','WRITE_OFF_NONE_RETURNED') DEFAULT NULL,
  `tasq_order_number` varchar(50) DEFAULT NULL,
  `next_calltag_notify_time` timestamp NULL DEFAULT NULL,
  `created_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `serial_number` (`serial_number`),
  KEY `merchant_id` (`merchant_id`),
  KEY `reseller_id` (`reseller_id`),
  KEY `deleted_time` (`deleted_time`),
  KEY `idx_chip_uid` (`chip_uid`),
  CONSTRAINT `device_provision_ibfk_1` FOREIGN KEY (`merchant_id`) REFERENCES `merchant` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `device_provision_ibfk_2` FOREIGN KEY (`reseller_id`) REFERENCES `reseller` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=996621 DEFAULT CHARSET=utf8mb3