CREATE TABLE `reseller_permissions` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `uuid` char(13) CHARACTER SET latin1 NOT NULL,
  `reseller_id` bigint unsigned NOT NULL,
  `type` enum('CS','Sales','Super','FACTORY_OPS','SIM_VIEWER') NOT NULL DEFAULT 'CS',
  `is_default` tinyint(1) DEFAULT '0',
  `name` varchar(255) NOT NULL,
  `view_merchant_dash` tinyint(1) NOT NULL DEFAULT '0',
  `create_new_merchant` tinyint(1) NOT NULL DEFAULT '0',
  `invite_owner` tinyint(1) NOT NULL DEFAULT '0',
  `deactivate_member` tinyint(1) NOT NULL DEFAULT '0',
  `support_remote_view` tinyint(1) NOT NULL DEFAULT '0',
  `edit_merchant_details` tinyint(1) NOT NULL DEFAULT '0',
  `edit_merchant_plan` tinyint(1) NOT NULL DEFAULT '0',
  `edit_merchant_gateway` tinyint(1) NOT NULL DEFAULT '0',
  `edit_merchant_details_advanced` tinyint(1) NOT NULL DEFAULT '0',
  `edit_merchant_gateway_advanced` tinyint(1) NOT NULL DEFAULT '0',
  `sales_view_device_list` tinyint(1) NOT NULL DEFAULT '0',
  `sales_associate_devices` tinyint(1) NOT NULL DEFAULT '0',
  `sales_disassociate_devices` tinyint(1) NOT NULL DEFAULT '0',
  `sales_disassociate_stolen_devices` tinyint(1) NOT NULL DEFAULT '0',
  `sales_manage_promotions` tinyint(1) NOT NULL DEFAULT '0',
  `super_manage_accounts` tinyint(1) NOT NULL DEFAULT '0',
  `sales_order_demo_devices` tinyint(1) NOT NULL DEFAULT '0',
  `uninstall_apps` tinyint(1) NOT NULL DEFAULT '0',
  `factory_ops_manage_accounts` tinyint(1) NOT NULL DEFAULT '0',
  `factory_ops_view_factory_reset_codes` tinyint(1) NOT NULL DEFAULT '0',
  `sim_viewer_view_sims` tinyint(1) NOT NULL DEFAULT '0',
  `sim_viewer_manage_accounts` tinyint(1) NOT NULL DEFAULT '0',
  `sim_viewer_create_sims` tinyint(1) NOT NULL DEFAULT '0',
  `modify_role_permissions` tinyint(1) NOT NULL DEFAULT '0',
  `assign_reseller_roles` tinyint(1) NOT NULL DEFAULT '0',
  `view_members` tinyint(1) NOT NULL DEFAULT '0',
  `invite_member` tinyint(1) NOT NULL DEFAULT '0',
  `create_reseller_role` tinyint(1) NOT NULL DEFAULT '0',
  `delete_reseller_role` tinyint(1) NOT NULL DEFAULT '0',
  `close_failed_batch` tinyint(1) NOT NULL DEFAULT '0',
  `view_failed_batch` tinyint(1) NOT NULL DEFAULT '0',
  `disassociate_reseller_account` tinyint(1) NOT NULL DEFAULT '0',
  `delete_account_auth_factor` tinyint(1) NOT NULL DEFAULT '0',
  `view_enterprise_dash` tinyint(1) NOT NULL DEFAULT '0',
  `billing_operations` tinyint(1) NOT NULL DEFAULT '0',
  `edit_app_billing_suppression` tinyint(1) NOT NULL DEFAULT '0',
  `edit_plan_billing_suppression` tinyint(1) NOT NULL DEFAULT '0',
  `edit_apps_billing_suppression` tinyint(1) NOT NULL DEFAULT '0',
  `create_reseller` tinyint(1) NOT NULL DEFAULT '0',
  `update_rapid_deposit_rules` tinyint(1) NOT NULL DEFAULT '0',
  `view_merchant_details` tinyint(1) NOT NULL DEFAULT '0',
  `move_devices_across_reseller` tinyint(1) NOT NULL DEFAULT '0',
  `modify_time_restrictions` tinyint(1) NOT NULL DEFAULT '0',
  `support_remote_view_only` tinyint(1) NOT NULL DEFAULT '0',
  `request_refunds` tinyint(1) NOT NULL DEFAULT '0',
  `modify_member_auth_factors` tinyint(1) NOT NULL DEFAULT '0',
  `modify_reseller` tinyint(1) NOT NULL DEFAULT '0',
  `edit_client_id` tinyint(1) NOT NULL DEFAULT '0',
  `modify_entitlements` tinyint(1) NOT NULL DEFAULT '0',
  `transfer_merchants` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uuid` (`uuid`),
  KEY `reseller_id` (`reseller_id`),
  CONSTRAINT `reseller_permissions_ibfk_1` FOREIGN KEY (`reseller_id`) REFERENCES `reseller` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=126835 DEFAULT CHARSET=utf8mb3