CREATE TABLE `biie_file_staging_data` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `biie_file_instance_id` bigint unsigned NOT NULL,
  `record_num` bigint unsigned NOT NULL,
  `record_status` enum('ERROR','PENDING','PROCESSED','SKIPPED','FIXED','WARNING') NOT NULL,
  `reason_code` smallint unsigned DEFAULT '0',
  `reason_detail` text,
  `created_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `raw_record` text,
  `field1` varchar(100) DEFAULT NULL,
  `field2` varchar(100) DEFAULT NULL,
  `field3` varchar(100) DEFAULT NULL,
  `field4` varchar(100) DEFAULT NULL,
  `field5` varchar(100) DEFAULT NULL,
  `field6` varchar(100) DEFAULT NULL,
  `field7` varchar(100) DEFAULT NULL,
  `field8` varchar(100) DEFAULT NULL,
  `field9` varchar(100) DEFAULT NULL,
  `field10` varchar(100) DEFAULT NULL,
  `field11` varchar(100) DEFAULT NULL,
  `field12` varchar(100) DEFAULT NULL,
  `field13` varchar(100) DEFAULT NULL,
  `field14` varchar(100) DEFAULT NULL,
  `field15` varchar(100) DEFAULT NULL,
  `field16` varchar(100) DEFAULT NULL,
  `field17` varchar(100) DEFAULT NULL,
  `field18` varchar(100) DEFAULT NULL,
  `field19` varchar(100) DEFAULT NULL,
  `field20` varchar(100) DEFAULT NULL,
  `key1` varchar(100) DEFAULT NULL,
  `key2` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `biie_fsd_instance_recnum` (`biie_file_instance_id`,`record_num`),
  KEY `biie_fsd_key1` (`key1`,`biie_file_instance_id`,`record_num`),
  KEY `biie_fsd_key2` (`key2`,`biie_file_instance_id`,`record_num`)
) ENGINE=InnoDB AUTO_INCREMENT=149969184 DEFAULT CHARSET=utf8mb3