CREATE TABLE `merchant_suppression` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `uuid` char(13) CHARACTER SET latin1 NOT NULL,
  `reference_id` bigint unsigned NOT NULL,
  `plan_billable` tinyint(1) DEFAULT '1',
  `app_billable` tinyint(1) DEFAULT '1',
  `plan_exportable` tinyint(1) DEFAULT '1',
  `app_exportable` tinyint(1) DEFAULT '1',
  `context` enum('OFF_BOARDED','TRIAL','ACH_HOLD','DEMO','OFFER','OVERRIDE','FIELD_TEST','DEBIT_NO_AUTH','PROMO','SEASONAL','FINANCE_EXCEPTION') NOT NULL,
  `detail` varchar(511) CHARACTER SET latin1 DEFAULT NULL,
  `start_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `finalization_time` timestamp NULL DEFAULT NULL,
  `finalize` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uuid` (`uuid`),
  KEY `merchant_sup_refid_idx` (`reference_id`),
  KEY `merchant_sup_idx` (`context`,`start_time`,`finalization_time`)
) ENGINE=InnoDB AUTO_INCREMENT=6961868 DEFAULT CHARSET=utf8mb3