CREATE TABLE `merchant_app` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `uuid` char(13) NOT NULL,
  `app_id` bigint unsigned NOT NULL,
  `merchant_id` int unsigned NOT NULL,
  `app_subscription_id` bigint unsigned NOT NULL,
  `billing_start_time` timestamp NULL DEFAULT NULL,
  `deleted_time` timestamp NULL DEFAULT NULL,
  `permission_merchant_read` tinyint(1) DEFAULT '0',
  `permission_merchant_write` tinyint(1) DEFAULT '0',
  `permission_process_cards` tinyint(1) NOT NULL DEFAULT '0',
  `permission_mid_read` tinyint(1) DEFAULT '0',
  `permission_customers_read` tinyint(1) DEFAULT '0',
  `permission_customers_write` tinyint(1) DEFAULT '0',
  `permission_customers_address_read` tinyint unsigned DEFAULT '0',
  `permission_customers_address_write` tinyint unsigned DEFAULT '0',
  `permission_customers_email_read` tinyint unsigned DEFAULT '0',
  `permission_customers_email_write` tinyint unsigned DEFAULT '0',
  `permission_customers_phone_read` tinyint unsigned DEFAULT '0',
  `permission_customers_phone_write` tinyint unsigned DEFAULT '0',
  `permission_customers_businessname_read` tinyint unsigned DEFAULT '0',
  `permission_customers_businessname_write` tinyint unsigned DEFAULT '0',
  `permission_customers_birthdate_read` tinyint unsigned DEFAULT '0',
  `permission_customers_birthdate_write` tinyint unsigned DEFAULT '0',
  `permission_customers_note_read` tinyint unsigned DEFAULT '0',
  `permission_customers_note_write` tinyint unsigned DEFAULT '0',
  `permission_customers_card_read` tinyint unsigned DEFAULT '0',
  `permission_customers_card_write` tinyint unsigned DEFAULT '0',
  `permission_customers_ach_read` tinyint unsigned DEFAULT '0',
  `permission_customers_ach_write` tinyint unsigned DEFAULT '0',
  `permission_customers_marketing_read` tinyint unsigned DEFAULT '0',
  `permission_customers_marketing_write` tinyint unsigned DEFAULT '0',
  `permission_inventory_read` tinyint(1) DEFAULT '0',
  `permission_inventory_write` tinyint(1) DEFAULT '0',
  `permission_orders_read` tinyint(1) DEFAULT '0',
  `permission_orders_write` tinyint(1) DEFAULT '0',
  `permission_payments_read` tinyint(1) DEFAULT '0',
  `permission_payments_write` tinyint(1) DEFAULT '0',
  `permission_employees_read` tinyint(1) DEFAULT '0',
  `permission_employees_write` tinyint(1) DEFAULT '0',
  `launched_in_web_browser_count` int unsigned NOT NULL DEFAULT '0',
  `created_time` timestamp NULL DEFAULT NULL,
  `modified_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `uninstall_type` enum('APP_BUNDLE_CHANGE','APP_SUNSET','MERCHANT_OFF_BOARDING','MERCHANT_PLAN_CHANGE','MERCHANT_UNINSTALL','MERCHANT_CONTROL') DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uuid` (`uuid`),
  KEY `app_id` (`app_id`),
  KEY `merchant_id_app_id` (`merchant_id`,`app_id`),
  KEY `created_time` (`created_time`),
  KEY `deleted_time` (`deleted_time`),
  KEY `idx_composite_merchant_app` (`app_subscription_id`,`app_id`,`deleted_time`),
  KEY `ma_billing_start_time_idx` (`billing_start_time`),
  CONSTRAINT `__merchant_app_ibfk_1` FOREIGN KEY (`app_id`) REFERENCES `developer_app` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `__merchant_app_ibfk_2` FOREIGN KEY (`app_subscription_id`) REFERENCES `app_subscription` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=291869464 DEFAULT CHARSET=utf8mb3