CREATE TABLE `merchant_plan` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `uuid` char(13) NOT NULL,
  `name` varchar(31) NOT NULL,
  `type` enum('PAYMENTS_PLUS','REGISTER_LITE','CLASSIC','REGISTER','QSR','DINING','NO_HARDWARE','PAYMENTS','SERVICES','RETAIL') DEFAULT NULL,
  `plan_code` varchar(50) DEFAULT NULL,
  `app_bundle_id` bigint unsigned NOT NULL,
  `description` varchar(2047) DEFAULT NULL,
  `reseller_id` bigint unsigned DEFAULT NULL,
  `merchant_plan_group_id` bigint unsigned DEFAULT NULL,
  `activation_time` timestamp NULL DEFAULT NULL,
  `deactivation_time` timestamp NULL DEFAULT NULL,
  `bill_to_mid` tinyint(1) DEFAULT '0',
  `enforced` tinyint(1) DEFAULT '0',
  `created_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `default_plan` tinyint(1) NOT NULL DEFAULT '0',
  `hidden` tinyint(1) DEFAULT '0',
  `tags` varchar(2047) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uuid` (`uuid`),
  KEY `app_bundle_ibfk_1` (`app_bundle_id`),
  CONSTRAINT `_app_bundle_ibfk_1` FOREIGN KEY (`app_bundle_id`) REFERENCES `app_bundle` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=654 DEFAULT CHARSET=latin1