CREATE TABLE `cycle_validation` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `uuid` char(26) NOT NULL,
  `task_id` varchar(126) NOT NULL,
  `task_type` enum('PRODUCER','CONSUMER') NOT NULL,
  `validation_group` varchar(126) NOT NULL,
  `billing_entity_uuid` char(26) NOT NULL,
  `hierarchy_type` varchar(20) NOT NULL,
  `cycle_date` date NOT NULL,
  `currency` char(3) NOT NULL,
  `status` varchar(25) NOT NULL,
  `bypass_count` decimal(12,4) NOT NULL,
  `bypass_amount` decimal(12,3) NOT NULL,
  `accepted_count` decimal(12,4) NOT NULL,
  `accepted_amount` decimal(12,3) NOT NULL,
  `total_count` decimal(12,4) NOT NULL,
  `total_amount` decimal(12,3) NOT NULL,
  `request_uuid` char(26) DEFAULT NULL,
  `validation_request_uuid` varchar(26) DEFAULT NULL,
  `created_timestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `modified_timestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `cycle_validation_key1` (`uuid`),
  UNIQUE KEY `cycle_validation_key2` (`request_uuid`,`billing_entity_uuid`,`hierarchy_type`,`task_id`,`id`),
  UNIQUE KEY `cycle_validation_key3` (`validation_request_uuid`,`billing_entity_uuid`,`hierarchy_type`,`task_id`,`id`),
  KEY `cycle_validation_index1` (`task_type`,`validation_group`,`billing_entity_uuid`,`hierarchy_type`,`status`),
  KEY `cycle_validation_index2` (`task_type`,`validation_group`,`billing_entity_uuid`,`hierarchy_type`,`cycle_date`,`status`)
) ENGINE=InnoDB AUTO_INCREMENT=4973 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci