CREATE TABLE `stage_charge_history` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `charge_id` bigint unsigned NOT NULL,
  `old_status` enum('PENDING','IN_PROGRESS','BILLED','CANCELED','REFUND_PENDING','REFUND_PENDING_IF_BILLED','REFUND_IN_PROGRESS','REFUNDED','REFUND_DOWNGRADE_PENDING','REFUND_DOWNGRADE_IN_PROGRESS','REFUND_DOWNGRADE_CANCELED','REFUNDED_DOWNGRADE','DISBURSED','ACH_REJECT','RESUBMITTED','INCURRED','REFUND_INCURRED','REFUND_INCURRED_IF_BILLED','REFUND_DOWNGRADE_INCURRED','REFUND_ACH_REJECT','REFUND_DOWNGRADE_ACH_REJECT','REFUND_CANCELED','WAIVED','REFUND_WAIVED','REFUND_DOWNGRADE_WAIVED','WRITTEN_OFF','REFUND_WRITTEN_OFF','REFUND_DOWNGRADE_WRITTEN_OFF','REVERSED','REFUND_REVERSED','REFUND_DOWNGRADE_REVERSED') NOT NULL,
  `old_developer_status` enum('DISBURSED','DISBURSE_FAILED','DISBURSE_PENDING','RECLAIMED','RECLAIM_FAILED','RECLAIM_PENDING') DEFAULT NULL,
  `old_status_owner` varchar(30) NOT NULL,
  `old_modified_time` timestamp NULL DEFAULT NULL,
  `created_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `request_uuid` char(13) NOT NULL,
  `promoted_time` timestamp NULL DEFAULT NULL,
  `promoted_id` bigint unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `app_line_item_id` (`charge_id`),
  KEY `request_uuid` (`request_uuid`)
) ENGINE=InnoDB AUTO_INCREMENT=729 DEFAULT CHARSET=utf8mb3