CREATE TABLE `cycle_validation_mutation` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `mutation_action` enum('UPDATE','DELETE') NOT NULL,
  `mutation_timestamp` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `cycle_validation_id` bigint unsigned NOT NULL,
  `uuid` char(26) NOT NULL,
  `task_id` varchar(126) DEFAULT NULL,
  `task_type` enum('PRODUCER','CONSUMER') DEFAULT NULL,
  `validation_group` varchar(126) DEFAULT NULL,
  `billing_entity_uuid` char(26) DEFAULT NULL,
  `hierarchy_type` varchar(20) DEFAULT NULL,
  `cycle_date` date DEFAULT NULL,
  `currency` char(3) DEFAULT NULL,
  `status` varchar(25) DEFAULT NULL,
  `bypass_count` decimal(12,4) DEFAULT NULL,
  `bypass_amount` decimal(12,3) DEFAULT NULL,
  `accepted_count` decimal(12,4) DEFAULT NULL,
  `accepted_amount` decimal(12,3) DEFAULT NULL,
  `total_count` decimal(12,4) DEFAULT NULL,
  `total_amount` decimal(12,3) DEFAULT NULL,
  `request_uuid` char(26) DEFAULT NULL,
  `validation_request_uuid` char(26) DEFAULT NULL,
  `created_timestamp` datetime(6) DEFAULT NULL,
  `modified_timestamp` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `cycle_validation_mutation_key1` (`uuid`,`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1087 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci