CREATE TABLE `stage_infolease_disbursement_attempt` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `uuid` char(13) CHARACTER SET latin1 NOT NULL,
  `charge_id` bigint unsigned NOT NULL,
  `type` varchar(5) DEFAULT NULL,
  `vendor_name` varchar(50) DEFAULT NULL,
  `payment_type` varchar(10) DEFAULT NULL,
  `payment_description` varchar(30) DEFAULT NULL,
  `contract_number` varchar(30) DEFAULT NULL,
  `inventory_number` varchar(30) DEFAULT NULL,
  `inventory_amount` bigint DEFAULT NULL,
  `inventory_date` varchar(10) DEFAULT NULL,
  `due_date` varchar(10) DEFAULT NULL,
  `gl_code` varchar(10) DEFAULT NULL,
  `inventory_status_date` varchar(10) DEFAULT NULL,
  `inventory_status_time` varchar(10) DEFAULT NULL,
  `created_time` timestamp NULL DEFAULT NULL,
  `modified_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `request_uuid` char(13) NOT NULL,
  `promoted_time` timestamp NULL DEFAULT NULL,
  `promoted_id` bigint unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `request_and_uuid` (`request_uuid`,`uuid`),
  UNIQUE KEY `sida_idx1` (`charge_id`,`promoted_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3