CREATE TABLE `developer` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `uuid` char(13) CHARACTER SET latin1 NOT NULL,
  `approval_status` enum('NEW','PENDING','APPROVED','DENIED') NOT NULL DEFAULT 'NEW',
  `collection_approval_status` enum('NEW','PENDING','APPROVED','DENIED') NOT NULL DEFAULT 'NEW',
  `secret` char(36) CHARACTER SET latin1 NOT NULL,
  `owner_account_id` int unsigned NOT NULL,
  `name` varchar(127) NOT NULL,
  `first_name` varchar(127) DEFAULT NULL,
  `last_name` varchar(127) DEFAULT NULL,
  `email` varchar(127) DEFAULT NULL,
  `phone` varchar(25) DEFAULT NULL,
  `dob` char(10) DEFAULT NULL,
  `address` varchar(255) DEFAULT NULL,
  `city` varchar(127) DEFAULT NULL,
  `county` varchar(127) DEFAULT NULL,
  `state` varchar(127) DEFAULT NULL,
  `country` char(2) DEFAULT NULL,
  `postal_code` varchar(20) DEFAULT NULL,
  `bank_routing_number` varchar(40) DEFAULT NULL,
  `tin` varchar(127) DEFAULT NULL,
  `tin_dps_uuid` varchar(127) DEFAULT NULL,
  `vat_register_number` varchar(127) DEFAULT NULL,
  `vat_dps_uuid` varchar(127) DEFAULT NULL,
  `business_legal_name` varchar(255) DEFAULT NULL,
  `business_address` varchar(255) DEFAULT NULL,
  `business_city` varchar(127) DEFAULT NULL,
  `business_state` varchar(127) DEFAULT NULL,
  `business_country` char(2) DEFAULT NULL,
  `business_postal_code` varchar(20) DEFAULT NULL,
  `billing_status` enum('PENDING','APPROVED','DECLINED','ERROR') DEFAULT NULL,
  `billing_status_message` varchar(127) DEFAULT NULL,
  `accepted_agreement` tinyint(1) NOT NULL DEFAULT '0',
  `pr_name` varchar(255) DEFAULT NULL,
  `pr_email` varchar(127) DEFAULT NULL,
  `pr_phone` varchar(25) DEFAULT NULL,
  `website` varchar(255) DEFAULT NULL,
  `created_time` timestamp NULL DEFAULT NULL,
  `first_submitted_time` timestamp NULL DEFAULT NULL,
  `first_approval_time` timestamp NULL DEFAULT NULL,
  `modified_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `sensitive_data` text,
  `infolease_vendor_code` varchar(30) DEFAULT NULL,
  `infolease_gl_code` varchar(10) DEFAULT NULL,
  `rev_share` int unsigned DEFAULT '7000',
  `is_rev_share_flat_rate` tinyint(1) DEFAULT '0',
  `signor_name` varchar(127) DEFAULT NULL,
  `signor_title` varchar(127) DEFAULT NULL,
  `referral_submission_time` timestamp NULL DEFAULT NULL,
  `billing_contract_number` varchar(128) DEFAULT NULL,
  `emergency_email` varchar(127) DEFAULT NULL,
  `developer_type` enum('EXTERNAL','CLOVERDEV','SECONDPARTY','CLOVERCONNECTISV','PARTNER') DEFAULT 'EXTERNAL',
  `approval_status_modified_time` timestamp NULL DEFAULT NULL,
  `tax_residency_country` char(2) DEFAULT NULL,
  `indirect_tax_dps_uuid` varchar(127) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uuid` (`uuid`),
  UNIQUE KEY `infolease_vendor_code` (`infolease_vendor_code`),
  KEY `owner_account_id` (`owner_account_id`),
  CONSTRAINT `developer_ibfk_1` FOREIGN KEY (`owner_account_id`) REFERENCES `account` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=201 DEFAULT CHARSET=utf8mb3