CREATE TABLE `account` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `uuid` char(13) CHARACTER SET latin1 NOT NULL,
  `name` varchar(127) DEFAULT NULL,
  `email` varchar(127) CHARACTER SET latin1 DEFAULT NULL,
  `primary_merchant_role_id` bigint unsigned DEFAULT NULL,
  `primary_developer_role_id` bigint unsigned DEFAULT NULL,
  `primary_reseller_role_id` bigint unsigned DEFAULT NULL,
  `password_hash` char(60) CHARACTER SET latin1 DEFAULT NULL,
  `oauth_provider` enum('google') DEFAULT NULL,
  `claim_code` varchar(255) DEFAULT NULL,
  `locked_out` tinyint(1) DEFAULT '0',
  `password_updated_time` timestamp NULL DEFAULT NULL,
  `is_active` tinyint(1) DEFAULT '1',
  `created_time` timestamp NULL DEFAULT NULL,
  `claimed_time` timestamp NULL DEFAULT NULL,
  `last_login` timestamp NULL DEFAULT NULL,
  `invite_sent` tinyint(1) DEFAULT '0',
  `auth_issuer` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uuid` (`uuid`),
  UNIQUE KEY `email` (`email`),
  KEY `primary_merchant_role_id` (`primary_merchant_role_id`),
  KEY `primary_developer_role_id` (`primary_developer_role_id`),
  KEY `primary_reseller_role_id` (`primary_reseller_role_id`),
  KEY `name` (`name`),
  CONSTRAINT `account_ibfk_1` FOREIGN KEY (`primary_merchant_role_id`) REFERENCES `merchant_role` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `account_ibfk_2` FOREIGN KEY (`primary_developer_role_id`) REFERENCES `developer_role` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `account_ibfk_3` FOREIGN KEY (`primary_reseller_role_id`) REFERENCES `reseller_role` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=22641 DEFAULT CHARSET=utf8mb3