CREATE TABLE `merchant_boarding` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `merchant_id` int unsigned NOT NULL,
  `bill_to_name` varchar(50) DEFAULT NULL,
  `merchant_data` varchar(20) DEFAULT NULL,
  `store` varchar(30) DEFAULT NULL,
  `daylight_savings` tinyint(1) DEFAULT NULL,
  `seasonal` tinyint(1) DEFAULT NULL,
  `trans_armor_key` varchar(11) DEFAULT NULL,
  `ach_bank_id` varchar(15) DEFAULT NULL,
  `credit_limit` int DEFAULT NULL,
  `auth_limit` int DEFAULT NULL,
  `sale_limit` int DEFAULT NULL,
  `account_status` varchar(23) DEFAULT NULL,
  `tax_exempt` tinyint(1) DEFAULT NULL,
  `salesman` varchar(24) DEFAULT NULL,
  `value_link` tinyint(1) DEFAULT NULL,
  `value_link_mid` varchar(11) DEFAULT NULL,
  `alt_value_link_mid` varchar(11) DEFAULT NULL,
  `receipt_dba` varchar(22) DEFAULT NULL,
  `bank_number` varchar(22) DEFAULT NULL,
  `parent_merchant_id` varchar(16) DEFAULT NULL,
  `relationship_manager` varchar(3) DEFAULT NULL,
  `multi_merchant_type` varchar(1) DEFAULT NULL,
  `external_merchant` tinyint(1) DEFAULT NULL,
  `dynamic_dba` tinyint(1) DEFAULT NULL,
  `fax_phone` varchar(10) DEFAULT NULL,
  `merchant_type` varchar(125) DEFAULT NULL,
  `multi_currency_indicator` varchar(50) DEFAULT NULL,
  `preferred_merchant` varchar(1) DEFAULT NULL,
  `visa_iram` varchar(1) DEFAULT NULL,
  `trans_armor_indicator` varchar(100) DEFAULT NULL,
  `signing_key` varchar(2) DEFAULT NULL,
  `visa_debit_accept` varchar(1) DEFAULT NULL,
  `mastercard_debit_accept` varchar(1) DEFAULT NULL,
  `source_indicator` varchar(1) DEFAULT NULL,
  `foreign_domestic_indicator` varchar(1) DEFAULT NULL,
  `account_funding` varchar(1) DEFAULT NULL,
  `direct_marketing` varchar(1) DEFAULT NULL,
  `participant_relationship` varchar(1) DEFAULT NULL,
  `process_settlement` varchar(1) DEFAULT NULL,
  `recurring_flag` varchar(1) DEFAULT NULL,
  `link_from` varchar(9) DEFAULT NULL,
  `link_to` varchar(9) DEFAULT NULL,
  `emv_allowed` varchar(1) DEFAULT NULL,
  `previous_account_status` varchar(2) DEFAULT NULL,
  `lease_company_code` varchar(2) DEFAULT NULL,
  `process_mode` tinyint(1) DEFAULT NULL,
  `agent_bank_indicator` varchar(1) DEFAULT NULL,
  `non_mpa_indicator` varchar(1) DEFAULT NULL,
  `internet_indicator` varchar(1) DEFAULT NULL,
  `charge_back_retrieval_address_flag` varchar(1) DEFAULT NULL,
  `vi_relationship_participant` varchar(1) DEFAULT NULL,
  `retail_description` varchar(22) DEFAULT NULL,
  `client_representative` varchar(30) DEFAULT NULL,
  `merchant_auth_type` varchar(1) DEFAULT NULL,
  `sys_prin` varchar(10) DEFAULT NULL,
  `tax_id` varchar(40) DEFAULT NULL,
  `business_type` varchar(15) DEFAULT NULL,
  `partner_id` varchar(64) DEFAULT NULL,
  `created_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `account_status_modified_time` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `merchant_id` (`merchant_id`),
  KEY `merchant_boarding_modified_time_idx` (`modified_time`),
  CONSTRAINT `merchant_boarding_ibfk_1` FOREIGN KEY (`merchant_id`) REFERENCES `merchant` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=80187 DEFAULT CHARSET=utf8mb3