CREATE TABLE `merchant` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `uuid` char(13) CHARACTER SET latin1 NOT NULL,
  `name` varchar(127) NOT NULL,
  `reseller_id` bigint unsigned NOT NULL,
  `owner_account_id` bigint unsigned NOT NULL,
  `address_id` int unsigned DEFAULT NULL,
  `timezone_id` bigint unsigned DEFAULT NULL,
  `default_currency` char(3) CHARACTER SET latin1 NOT NULL,
  `phone_number` varchar(21) DEFAULT NULL,
  `website` varchar(255) DEFAULT NULL,
  `created_time` timestamp NULL DEFAULT NULL,
  `merchant_gateway_id` int unsigned DEFAULT NULL,
  `merchant_plan_id` bigint unsigned DEFAULT NULL,
  `tax_rate` int unsigned DEFAULT NULL,
  `tips_enabled` tinyint(1) DEFAULT '0',
  `receipt_properties` text,
  `summary_hour` smallint NOT NULL DEFAULT '0',
  `last_summary_order_id` bigint unsigned DEFAULT NULL,
  `subscription_id` bigint unsigned DEFAULT NULL,
  `levelup_auth_token` varchar(255) DEFAULT NULL,
  `levelup_merchant_id` bigint unsigned DEFAULT NULL,
  `levelup_location_id` bigint unsigned DEFAULT NULL,
  `signature_threshold` bigint unsigned DEFAULT '0',
  `tip_rate_default` int unsigned DEFAULT '1500',
  `on_paper_tip_signatures` tinyint(1) DEFAULT NULL,
  `force_signature_verify` tinyint(1) DEFAULT NULL,
  `auto_logout` tinyint(1) NOT NULL DEFAULT '0',
  `order_title` enum('none','manual','automatic') DEFAULT 'none',
  `order_title_max` int unsigned DEFAULT '99',
  `reset_on_reporting_time` tinyint(1) NOT NULL DEFAULT '0',
  `notes_on_orders` tinyint(1) NOT NULL DEFAULT '0',
  `delete_orders` tinyint(1) NOT NULL DEFAULT '1',
  `cash_management_enabled` tinyint(1) NOT NULL DEFAULT '1',
  `remove_tax_enabled` tinyint(1) NOT NULL DEFAULT '0',
  `group_line_items` tinyint(1) NOT NULL DEFAULT '1',
  `alternate_inventory_names` tinyint(1) NOT NULL DEFAULT '0',
  `auto_print` tinyint(1) NOT NULL DEFAULT '0',
  `hardware_profile` varchar(127) DEFAULT NULL,
  `shipping_address` text,
  `marketing_preference_id` bigint unsigned DEFAULT NULL,
  `merchant_group_id` bigint unsigned DEFAULT NULL,
  `bank_marker` smallint unsigned DEFAULT NULL,
  `support_phone` varchar(25) DEFAULT NULL,
  `support_email` varchar(127) DEFAULT NULL,
  `debug_enabled` tinyint(1) DEFAULT '0',
  `manual_closeout` tinyint(1) DEFAULT '0',
  `stay_in_category` tinyint(1) DEFAULT '0',
  `locale_id` bigint unsigned DEFAULT NULL,
  `is_vat` tinyint(1) NOT NULL,
  `vat_tax_name` varchar(255) DEFAULT NULL,
  `track_stock` tinyint(1) DEFAULT '0',
  `update_stock` tinyint(1) DEFAULT '0',
  `allow_clock_out_with_open_orders` tinyint(1) NOT NULL DEFAULT '0',
  `log_in_clock_in_prompt` tinyint(1) NOT NULL DEFAULT '1',
  `account_type` varchar(32) DEFAULT NULL,
  `pin_length` tinyint(1) NOT NULL DEFAULT '4',
  `cash_back_enabled` tinyint(1) NOT NULL DEFAULT '0',
  `max_cash_back` bigint unsigned DEFAULT NULL,
  `business_type_code` enum('FULL_SERVICE_RESTAURANT','QUICK_SERVICE_RESTAURANT','COFFEE_SHOP','BAKERY','BAR','FOOD_TRUCK','FROZEN_YOGURT','PIZZA','DELI','OTHER_RESTAURANT','BOUTIQUE','CONVENIENCE_STORE','GROCERY','LIQUOR_STORE','VAPE_SHOP','JEWELRY','FLORIST','OTHER_RETAIL','FITNESS','SPA','HAIR_SALON','HOME_AND_REPAIR','PROFESSIONAL_SERVICES','CATERING','OTHER_SERVICE') DEFAULT NULL,
  `hierarchy` varchar(255) DEFAULT NULL,
  `app_config_id` int DEFAULT NULL,
  `aba_account_number` varchar(40) DEFAULT NULL,
  `dda_account_number` varchar(40) DEFAULT NULL,
  `infolease_authorize_time` timestamp NULL DEFAULT NULL,
  `infolease_authorize_code` varchar(50) DEFAULT NULL,
  `infolease_suppress_billing` tinyint(1) NOT NULL DEFAULT '0',
  `infolease_suppress_plan_billing` tinyint(1) NOT NULL DEFAULT '0',
  `send_closeout_email` tinyint(1) DEFAULT '0',
  `cash_back_options` varchar(255) DEFAULT NULL,
  `cluster_id` int unsigned NOT NULL DEFAULT '0',
  `offline_opted_in` tinyint(1) DEFAULT NULL,
  `offline_job_notification_time` timestamp NULL DEFAULT NULL,
  `modified_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `customer_contact_email` varchar(127) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uuid` (`uuid`),
  KEY `reseller_id` (`reseller_id`),
  KEY `merchant_gateway_id` (`merchant_gateway_id`),
  KEY `last_summary_order_id` (`last_summary_order_id`),
  KEY `subscription_id` (`subscription_id`),
  KEY `timezone_id` (`timezone_id`),
  KEY `merchant_group_id` (`merchant_group_id`),
  KEY `locale_id` (`locale_id`),
  KEY `address_id` (`address_id`),
  KEY `name` (`name`),
  KEY `modified_time` (`modified_time`),
  KEY `owner_account_id` (`owner_account_id`),
  CONSTRAINT `merchant_ibfk_1` FOREIGN KEY (`reseller_id`) REFERENCES `reseller` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `merchant_ibfk_2` FOREIGN KEY (`merchant_gateway_id`) REFERENCES `merchant_gateway` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `merchant_ibfk_4` FOREIGN KEY (`subscription_id`) REFERENCES `subscription` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `merchant_ibfk_5` FOREIGN KEY (`address_id`) REFERENCES `merchant_address` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `merchant_ibfk_6` FOREIGN KEY (`timezone_id`) REFERENCES `timezones` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `merchant_ibfk_7` FOREIGN KEY (`merchant_group_id`) REFERENCES `merchant_group` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `merchant_ibfk_8` FOREIGN KEY (`locale_id`) REFERENCES `locale` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=82133 DEFAULT CHARSET=utf8mb3