CREATE TABLE `developer_app` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `uuid` char(13) CHARACTER SET latin1 NOT NULL,
  `approval_status` enum('NEW','PENDING','APPROVED','DENIED','PUBLISHED') NOT NULL DEFAULT 'NEW',
  `default_response_type` enum('token','code') DEFAULT 'code',
  `approval_status_modified_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_time` timestamp NULL DEFAULT NULL,
  `approval_android_version_id` bigint unsigned DEFAULT NULL,
  `approval_signature` blob,
  `system_app` tinyint(1) DEFAULT '0',
  `hidden` tinyint(1) NOT NULL DEFAULT '0',
  `distribution` enum('PUBLIC','PRIVATE') NOT NULL DEFAULT 'PUBLIC',
  `segment` enum('APP_MARKET','SEMI_INT','MERCHANT_COMPANION','CLOVER_GO') DEFAULT NULL,
  `ecomm_integration_type` enum('API','IFRAME','HOSTED_CHECKOUT') DEFAULT NULL,
  `developer_id` bigint unsigned NOT NULL,
  `name` varchar(250) DEFAULT NULL,
  `description` varchar(2047) DEFAULT NULL,
  `tagline` varchar(255) DEFAULT NULL,
  `benefits` varchar(2047) DEFAULT NULL,
  `video_url` varchar(255) DEFAULT NULL,
  `activation_url` varchar(255) DEFAULT NULL,
  `site_url` varchar(255) DEFAULT NULL,
  `launch_url_path` varchar(255) CHARACTER SET latin1 DEFAULT NULL,
  `app_domain` varchar(255) DEFAULT NULL,
  `android_version_id` bigint unsigned DEFAULT NULL,
  `package_name` varchar(255) CHARACTER SET latin1 DEFAULT NULL,
  `signature` blob,
  `sort_order` int unsigned DEFAULT '0',
  `filename_icon` varchar(100) CHARACTER SET latin1 DEFAULT NULL,
  `filename_banner` varchar(255) CHARACTER SET latin1 DEFAULT NULL,
  `filename_cover` varchar(255) CHARACTER SET latin1 DEFAULT NULL,
  `product_type` enum('ANDROID','WEB','BOTH','EMBEDDED') DEFAULT NULL,
  `paid_app_has_trial` tinyint(1) NOT NULL DEFAULT '0',
  `smart_receipt_text` varchar(100) DEFAULT NULL,
  `smart_receipt_url` varchar(255) DEFAULT NULL,
  `request_limit` int unsigned NOT NULL DEFAULT '50',
  `merchant_request_limit` int unsigned NOT NULL DEFAULT '16',
  `concurrent_request_limit` int unsigned NOT NULL DEFAULT '10',
  `concurrent_merchant_request_limit` int unsigned NOT NULL DEFAULT '5',
  `privacy_policy` varchar(255) DEFAULT NULL,
  `eula` varchar(255) DEFAULT NULL,
  `support_phone` varchar(25) DEFAULT NULL,
  `support_phone_hours` varchar(127) DEFAULT NULL,
  `support_email` varchar(127) DEFAULT NULL,
  `support_url` varchar(255) DEFAULT NULL,
  `modified_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `authtoken_refresh_time` timestamp NULL DEFAULT NULL,
  `tax_classification_code` varchar(10) DEFAULT NULL,
  `application_id` varchar(255) DEFAULT NULL,
  `partner_id` varchar(64) DEFAULT NULL,
  `fd_equipment_code` varchar(32) DEFAULT NULL,
  `fd_equipment_name` varchar(255) DEFAULT NULL,
  `non_clover_billing` tinyint(1) NOT NULL DEFAULT '0',
  `first_published_time` timestamp NULL DEFAULT NULL,
  `first_approval_time` timestamp NULL DEFAULT NULL,
  `first_submitted_time` timestamp NULL DEFAULT NULL,
  `created_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `white_list_private_api` tinyint(1) NOT NULL DEFAULT '0',
  `app_bundle_id` bigint unsigned DEFAULT NULL,
  `editor_pick` tinyint(1) DEFAULT '0',
  `install_count` int unsigned DEFAULT '0',
  `popularity` int DEFAULT '0',
  `rank` int NOT NULL DEFAULT '0',
  `link_label` varchar(125) DEFAULT NULL,
  `rejection_reason` varchar(2047) DEFAULT NULL,
  `trial_days` smallint unsigned NOT NULL DEFAULT '30',
  `recaptcha` tinyint(1) DEFAULT '0',
  `default_app_locale` char(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uuid` (`uuid`),
  UNIQUE KEY `partner_id` (`partner_id`),
  KEY `android_version_id` (`android_version_id`),
  KEY `approval_android_version_id` (`approval_android_version_id`),
  KEY `developer_id` (`developer_id`),
  KEY `name` (`name`),
  KEY `package_name` (`package_name`),
  KEY `sort_order` (`sort_order`),
  KEY `approval_status` (`approval_status`),
  KEY `deleted_status_hidden` (`deleted_time`,`approval_status`,`hidden`),
  KEY `app_domain` (`app_domain`),
  CONSTRAINT `developer_app_ibfk_2` FOREIGN KEY (`developer_id`) REFERENCES `developer` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `developer_app_ibfk_3` FOREIGN KEY (`android_version_id`) REFERENCES `android_version` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `developer_app_ibfk_4` FOREIGN KEY (`approval_android_version_id`) REFERENCES `android_version` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=541 DEFAULT CHARSET=utf8mb3