name: Test

on:
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'nix/**'
      - '*.nix'
      - 'pyproject.toml'
      - 'uv.lock'
      - '.github/**'
  push:
    branches:
      - main

jobs:
  test:
    runs-on: [ self-hosted ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Maybe my job is being rejected because of the actions below disabling them for now...
      # (steps.sh will fail if nix isn't installed, but that would still be progress)

      # - name: Install Nix
      #   uses: matt-rixman/nix-quick-install-action@main

      # - name: Restore and save Nix store
      #   uses: matt-rixman/cache-nix-action@main
      #   with:
      #     primary-key: nix-${{ hashFiles('**/*.nix', '**/flake.lock') }}
      #     restore-prefixes-first-match: nix-
      #     gc-max-store-size: 8G
      #     purge: true
      #     purge-prefixes: nix-
      #     purge-created: 0
      #     purge-last-accessed: 0
      #     purge-primary-key: never

      # This script uses nix to create a CI environment that's identical to the dev environment
      - name: Run steps.sh
        run: ./steps.sh
        env:
          CI: "1"
