name: Test

on:
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'nix/**'
      - '*.nix'
      - 'pyproject.toml'
      - 'uv.lock'
      - '.github/**'
  push:
    branches:
      - main

jobs:
  test:
    runs-on: [ self-hosted ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: ./.github/actions/install-nix

      - name: Restore and save Nix store
        uses: ./.github/actions/cache-nix
        with:
          primary-key: nix-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-
          paths: |
            ~/.nix-portable
          nix: false
          purge: true
          purge-prefixes: nix-
          purge-created: 0
          purge-last-accessed: 0
          purge-primary-key: never

      - name: Run steps.sh
        run: ./steps.sh
        env:
          CI: "1"
