apiVersion: v1
kind: Pod
metadata:
  name: mysql
  namespace: default
  labels:
    app: mysql
spec:
  containers:
  - name: mysql
    image: mysql:8.0
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "pass"
    - name: MYSQL_DATABASE
      value: "test"
    - name: MYSQL_USER
      value: "user"
    - name: MYSQL_PASSWORD
      value: "pass"
    ports:
    - containerPort: 3306
      name: mysql
    volumeMounts:
    - name: mysql-init-script
      mountPath: /docker-entrypoint-initdb.d
    readinessProbe:
      exec:
        command:
        - mysql
        - -h
        - localhost
        - -u
        - user
        - -ppass
        - -e
        - "SELECT 1"
      initialDelaySeconds: 30
      periodSeconds: 10
    livenessProbe:
      exec:
        command:
        - mysql
        - -h
        - localhost
        - -u
        - user
        - -ppass
        - -e
        - "SELECT 1"
      initialDelaySeconds: 60
      periodSeconds: 30
  volumes:
  - name: mysql-init-script
    configMap:
      name: mysql-init-script